### ISSUE TITLE
支持Velocity+Paper(1服),Purpur(2服)吗

### ISSUE THREAD

**Issue by Ericlyclyclyc** [tanyaofei/OneSync#4]
见标题.

**Comment by tanyaofei** [comment]
理论上purpur下游都可以，建议测试一下

**Comment by Ericlyclyclyc** [comment]
oka
lyc

________________________________
发件人: hello09x ***@***.***>
发送时间: 2024年12月25日 0:48
收件人: tanyaofei/OneSync ***@***.***>
抄送: Ericlyclyclyc ***@***.***>; Author ***@***.***>
主题: Re: [tanyaofei/OneSync] 支持Velocity+Paper(1服),Purpur(2服)吗 (Issue #4)


理论上purpur下游都可以，建议测试一下

―

**Comment by Ericlyclyclyc** [comment]
我先整个Folia Folia 试过吗

**Comment by Ericlyclyclyc** [comment]
Why???
`
[23:36:26] [Server thread/ERROR]: [OneSync] 加载插件失败, 为了数据安全, 关闭当前服务器!
java.lang.ExceptionInInitializerError
	at OneSync-0.0.5.jar//io.github.hello09x.onesync.manager.synchronize.LockingManager.<init>(LockingManager.java:30)
	at OneSync-0.0.5.jar//io.github.hello09x.onesync.manager.synchronize.LockingManager.<clinit>(LockingManager.java:24)
	at OneSync-0.0.5.jar//io.github.hello09x.onesync.command.impl.UnlockCommand.<init>(UnlockCommand.java:22)
	at OneSync-0.0.5.jar//io.github.hello09x.onesync.command.impl.UnlockCommand.<clinit>(UnlockCommand.java:21)
	at OneSync-0.0.5.jar//io.github.hello09x.onesync.command.SynchronizeCommandRegistry.register(SynchronizeCommandRegistry.java:21)
	at OneSync-0.0.5.jar//io.github.hello09x.onesync.Main.onEnable(Main.java:62)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:772)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:534)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.IllegalStateException: Failed to connect to database
	at OneSync-0.0.5.jar//io.github.hello09x.bedrock.database.ConnectPool.connect(ConnectPool.java:59)
	at OneSync-0.0.5.jar//io.github.hello09x.bedrock.database.ConnectPool.<init>(ConnectPool.java:51)
	at OneSync-0.0.5.jar//io.github.hello09x.bedrock.database.ConnectionPoolHolder.lambda$getOrCreate$0(ConnectionPoolHolder.java:25)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713)
	at OneSync-0.0.5.jar//io.github.hello09x.bedrock.database.ConnectionPoolHolder.getOrCreate(ConnectionPoolHolder.java:18)
	at OneSync-0.0.5.jar//io.github.hello09x.bedrock.database.Repository.<init>(Repository.java:31)
	at OneSync-0.0.5.jar//io.github.hello09x.onesync.repository.LockingRepository.<init>(LockingRepository.java:21)
	at OneSync-0.0.5.jar//io.github.hello09x.onesync.repository.LockingRepository.<clinit>(LockingRepository.java:18)
	... 18 more
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:837)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:420)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:682)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at OneSync-0.0.5.jar//io.github.hello09x.bedrock.database.ConnectPool.connect(ConnectPool.java:57)
	... 25 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:79)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:142)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:961)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
	... 31 more
Caused by: java.net.ConnectException: Connection refused: getsockopt
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:760)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:144)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:53)
	... 34 more

[23:36:26] [Server thread/ERROR]: Error occurred while enabling OneSync v0.0.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.manager.synchronize.LockingManager.<init>(LockingManager.java:30) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.manager.synchronize.LockingManager.<clinit>(LockingManager.java:24) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.command.impl.UnlockCommand.<init>(UnlockCommand.java:22) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.command.impl.UnlockCommand.<clinit>(UnlockCommand.java:21) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.command.SynchronizeCommandRegistry.register(SynchronizeCommandRegistry.java:21) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.Main.onEnable(Main.java:62) ~[OneSync-0.0.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:772) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:534) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.IllegalStateException: Failed to connect to database
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectPool.connect(ConnectPool.java:59) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectPool.<init>(ConnectPool.java:51) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectionPoolHolder.lambda$getOrCreate$0(ConnectionPoolHolder.java:25) ~[OneSync-0.0.5.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713) ~[?:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectionPoolHolder.getOrCreate(ConnectionPoolHolder.java:18) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.Repository.<init>(Repository.java:31) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.repository.LockingRepository.<init>(LockingRepository.java:21) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.repository.LockingRepository.<clinit>(LockingRepository.java:18) ~[OneSync-0.0.5.jar:?]
	... 18 more
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:837) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:420) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:682) ~[java.sql:?]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230) ~[java.sql:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectPool.connect(ConnectPool.java:57) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectPool.<init>(ConnectPool.java:51) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectionPoolHolder.lambda$getOrCreate$0(ConnectionPoolHolder.java:25) ~[OneSync-0.0.5.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713) ~[?:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectionPoolHolder.getOrCreate(ConnectionPoolHolder.java:18) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.Repository.<init>(Repository.java:31) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.repository.LockingRepository.<init>(LockingRepository.java:21) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.repository.LockingRepository.<clinit>(LockingRepository.java:18) ~[OneSync-0.0.5.jar:?]
	... 18 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:79) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:142) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:961) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:420) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:682) ~[java.sql:?]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230) ~[java.sql:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectPool.connect(ConnectPool.java:57) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectPool.<init>(ConnectPool.java:51) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectionPoolHolder.lambda$getOrCreate$0(ConnectionPoolHolder.java:25) ~[OneSync-0.0.5.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713) ~[?:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectionPoolHolder.getOrCreate(ConnectionPoolHolder.java:18) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.Repository.<init>(Repository.java:31) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.repository.LockingRepository.<init>(LockingRepository.java:21) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.repository.LockingRepository.<clinit>(LockingRepository.java:18) ~[OneSync-0.0.5.jar:?]
	... 18 more
Caused by: java.net.ConnectException: Connection refused: getsockopt
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.base/java.net.Socket.connect(Socket.java:760) ~[?:?]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:144) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:53) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:142) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:961) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:420) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:682) ~[java.sql:?]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230) ~[java.sql:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectPool.connect(ConnectPool.java:57) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectPool.<init>(ConnectPool.java:51) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectionPoolHolder.lambda$getOrCreate$0(ConnectionPoolHolder.java:25) ~[OneSync-0.0.5.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713) ~[?:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.ConnectionPoolHolder.getOrCreate(ConnectionPoolHolder.java:18) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.bedrock.database.Repository.<init>(Repository.java:31) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.repository.LockingRepository.<init>(LockingRepository.java:21) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.repository.LockingRepository.<clinit>(LockingRepository.java:18) ~[OneSync-0.0.5.jar:?]
	... 18 more
[23:36:26] [Server thread/INFO]: [OneSync] Disabling OneSync v0.0.5
[23:36:26] [Server thread/ERROR]: Error occurred while disabling OneSync v0.0.5
java.lang.NoClassDefFoundError: Could not initialize class io.github.hello09x.onesync.manager.synchronize.LockingManager
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.manager.synchronize.SynchronizeManager.<init>(SynchronizeManager.java:31) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.manager.synchronize.SynchronizeManager.<clinit>(SynchronizeManager.java:29) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.Main.onDisable(Main.java:120) ~[OneSync-0.0.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:772) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:534) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.manager.synchronize.LockingManager.<init>(LockingManager.java:30) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.manager.synchronize.LockingManager.<clinit>(LockingManager.java:24) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.command.impl.UnlockCommand.<init>(UnlockCommand.java:22) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.command.impl.UnlockCommand.<clinit>(UnlockCommand.java:21) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.command.SynchronizeCommandRegistry.register(SynchronizeCommandRegistry.java:21) ~[OneSync-0.0.5.jar:?]
	at OneSync-0.0.5.jar/io.github.hello09x.onesync.Main.onEnable(Main.java:62) ~[OneSync-0.0.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	... 10 more
`

**Comment by Ericlyclyclyc** [comment]
:(
):

**Comment by tanyaofei** [comment]
连不上数据库，你确定你电脑安装了数据库以及账号密码正确吗

**Comment by Ericlyclyclyc** [comment]
ok

**Comment by Ericlyclyclyc** [comment]
看上去非常肥肠安全
还自动关闭
